name: Selenium Grid CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.18.1
        ports:
          - 4444:4444

      chrome:
        image: selenium/node-chrome:4.18.1
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        options: --shm-size=2g

      firefox:
        image: selenium/node-firefox:4.18.1
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        options: --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Run Maven tests
        run: mvn clean test
        env:
          GRID_URL: http://localhost:4444


# name: Selenium Grid CI

# on:
#   push:
#   pull_request:

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     services:
#         chrome:
#             image: selenium/standalone-chrome:latest
#             ports:
#             - 4444:4444
#             options: --shm-size=2g

#         firefox:
#             image: selenium/standalone-firefox:latest
#             ports:
#             - 4445:4444
#             options: --shm-size=2g


#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Java
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '11'

#       - name: Run Maven tests
#         run: mvn clean test
#         env:
#             CHROME_GRID_URL: http://localhost:4444
#             FIREFOX_GRID_URL: http://localhost:4445


